### ISSUE TITLE
Sidebar Text border

### ISSUE THREAD

**Issue by kd2gfn** [superlou/otakon-node#18]
borders in sidebar like in main is needed because text can be hard to read depending in image displayed as backgroud

**Comment by superlou** [comment]
Can you get a screenshot of some of the backgrounds and text? Do we also
need to change text colors?

**Comment by superlou** [comment]
I can set a background image or color.

![image](https://github.com/user-attachments/assets/45531024-bcb1-4647-b568-fd3ff3599f27)
