### ISSUE TITLE
Z- split to straight split.

### ISSUE THREAD

**Issue by kd2gfn** [superlou/otakon-node#3]
1/3 and 2/3 panel need vertical split for Otakon

**Comment by superlou** [comment]
While doing this, I need to also remove the shader used to crop images, which should let us run at 4K.

**Comment by superlou** [comment]
Switched to a straight 1/3, 2/3 split:

![image](https://github.com/superlou/otakon-node/assets/709695/fb642674-b58d-4990-90e4-1c4f444686b4)

There are some small padding things to fix, but media should be 640x964 and 1280x964.
